api_params:
  original:
    temperature: 0.95
    max_tokens: 16384
    top_p: 0.95
    n: 1
    frequency_penalty: 0
    presence_penalty: 0
  reasoning_api_params:
    max_completion_tokens: 16384

